# ============ 1) Dependencies =============
FROM node:20-bookworm-slim AS deps
WORKDIR /app

# Install minimal OS deps for faster/cleaner npm ci (optional but useful)
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates git openssh-client \
 && rm -rf /var/lib/apt/lists/*

# Copy lockfiles to get reproducible installs
COPY package.json package-lock.json* ./

# Install exact dependencies for production build
RUN npm ci

# ============ 2) Builder =============
FROM node:20-bookworm-slim AS builder
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Copy node_modules and sources
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# IMPORTANT: Next.js standalone requires:
#   next.config.js =>  module.exports = { output: 'standalone' }
# Build the app
RUN npm run build

# ============ 3) Runner =============
FROM node:20-bookworm-slim AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Non-root user
RUN groupadd -g 1001 nodejs \
 && useradd -r -u 1001 -g nodejs nextjs

# Copy standalone server and static assets
# (this layout is generated by Next when output:'standalone')
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# Ownership + security
RUN chown -R nextjs:nodejs /app
USER nextjs

EXPOSE 3000

# Start Next.js standalone server.js emitted by Next
CMD ["node", "server.js"]
